# fly.toml app configuration file generated for cv-creator-backend on 2024-02-09T12:56:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zoltan-antal-cv-creator-backend'
primary_region = 'lhr'

[deploy]

[processes]
  app = "node index.js"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
